type: sim_puppeteer
name: sim_puppeteer_piper_2arm_table

teleop_dt: 0.02
output_type: joint_pos # 'joint_pos' or 'delta_eef_pose'

# for eef-based mapping
motion_mapping: follower_reprojection # 'direct_scaling', 'follower_reprojection', 'leader_reprojection'
motion_scale: 1.0

limb_joint_names:
  robot1: ['robot1/joint1', 'robot1/joint2', 'robot1/joint3', 'robot1/joint4', 'robot1/joint5', 'robot1/joint6']
  robot2: ['robot2/joint1', 'robot2/joint2', 'robot2/joint3', 'robot2/joint4', 'robot2/joint5', 'robot2/joint6']

end_effector_link:
  robot1: 'robot1/end_effector_link'
  robot2: 'robot2/end_effector_link'

hand_joint_names:
  robot1: ['robot1/gripper']
  robot2: ['robot2/gripper']

init_qpos: [0.5022, 1.0062, -0.8032, 0, 0.6269, 0, -0.5022, 1.0062, -0.8032, 0, 0.6269, 0, 0, 0]

# leader limb -> follower limb
direct_mapping: # default is empty, which means 1:1 mapping
  robot1: 'robot1'
  robot2: 'robot2'

asset_cfg:
  asset_dir: 'models/'
  urdf_path: 'models/leaders/papras_6dof_leaders_table.urdf'
  xml_path: 'models/leaders/papras_6dof_leaders_table.xml'

direct_mapping_available_robots: ['piper_2arm_table']

render_base: 'mujoco'
viewer_args:
    trimesh:
      pq: [-0.84400246, -0.74844073,  0.63149086,  0.79797548,  0.49961321, -0.17853849, -0.28591218]